[package]
name = "typst-lr1-parser-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "*"
lalrpop-util = { version = "0.19.7", features = ["lexer"] }
clipboard = "0.5.0"

[build-dependencies]
lalrpop = "0.19.7"
